# Generated by Django 4.1.7 on 2023-03-16 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_driver_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(db_index=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='language',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='mobileNumber',
            field=models.CharField(db_index=True, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='truck',
            name='plateNumber',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='registrationNumber',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
