# Generated by Django 4.1.7 on 2023-03-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_driver_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='driver',
            name='language',
        ),
        migrations.AddField(
            model_name='driver',
            name='language',
            field=models.ManyToManyField(to='api.language'),
        ),
    ]
