# Generated by Django 4.1.7 on 2023-03-16 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_language_remove_driver_language_driver_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='AasignedTruck',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.truck'),
        ),
    ]
