# Generated by Django 4.1.7 on 2023-03-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_driver_aasignedtruck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='language',
            field=models.ManyToManyField(related_name='languages', to='api.language'),
        ),
    ]
