# Generated by Django 4.1.7 on 2023-03-16 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_driver_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='AasignedTruck',
            new_name='aasignedTruck',
        ),
    ]
