# Generated by Django 4.1.7 on 2023-03-16 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_aasignedtruck_driver_aasignedtruck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='aasignedTruck',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='truck', to='api.truck'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='language',
            field=models.ManyToManyField(to='api.language'),
        ),
    ]
